### ISSUE TITLE
Installation not working: undefined BLAS reference

### ISSUE THREAD

**Issue by mirpie** [amcdavid/HurdleNormal#10]
I'm trying to install this package as a dependency for another package (COZINE), and I'm getting the following error:

```
C:\rtools45\x86_64-w64-mingw32.static.posix\bin/ld.exe: hurdle_likelihood.o:hurdle_likelihood.cpp:(.text+0x1fc): undefined reference to `ddot_'
C:\rtools45\x86_64-w64-mingw32.static.posix\bin/ld.exe: hurdle_likelihood.o:hurdle_likelihood.cpp:(.text+0x3be): undefined reference to `dsyrk_'
C:\rtools45\x86_64-w64-mingw32.static.posix\bin/ld.exe: hurdle_likelihood.o:hurdle_likelihood.cpp:(.text+0x6c8): undefined reference to `dgemv_'
C:\rtools45\x86_64-w64-mingw32.static.posix\bin/ld.exe: hurdle_likelihood.o:hurdle_likelihood.cpp:(.text+0x23f0): undefined reference to `dgemm_'
C:\rtools45\x86_64-w64-mingw32.static.posix\bin/ld.exe: hurdle_likelihood.o:hurdle_likelihood.cpp:(.text+0x49c4): undefined reference to `ddot_'
C:\rtools45\x86_64-w64-mingw32.static.posix\bin/ld.exe: hurdle_likelihood.o:hurdle_likelihood.cpp:(.text.hot+0x12c): undefined reference to `dgemv_'
C:\rtools45\x86_64-w64-mingw32.static.posix\bin/ld.exe: hurdle_likelihood.o:hurdle_likelihood.cpp:(.text.hot+0x263): undefined reference to `dgemv_'
C:\rtools45\x86_64-w64-mingw32.static.posix\bin/ld.exe: hurdle_likelihood.o:hurdle_likelihood.cpp:(.text.hot+0x3ba): undefined reference to `dgemv_'
C:\rtools45\x86_64-w64-mingw32.static.posix\bin/ld.exe: hurdle_likelihood.o:hurdle_likelihood.cpp:(.text.hot+0x7cc): undefined reference to `dgemv_'
C:\rtools45\x86_64-w64-mingw32.static.posix\bin/ld.exe: hurdle_likelihood.o:hurdle_likelihood.cpp:(.text.hot+0x882): undefined reference to `dgemv_'
collect2.exe: error: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'HurdleNormal'
* removing 'C:/Users/myname/AppData/Local/R/win-library/4.5/HurdleNormal'
```

It seems that the package can't find BLAS operations that other packages don't have an issue with. 

I have tried multiple troubleshooting steps like reinstalling Rtools, and installing alternative BLAS packages as a workaround, but I can't seem to get it to work.

If this is a bug in the source code I would appreciate an update to work with R 4.5!
